Flask_AI/D1023/DBWEB/models/models.py
# --------------------------------------------------------
# 데이터베이스의 테이블 정의 클래스
# --------------------------------------------------------

# 모듈로딩
from DBWEB import DB


# --------------------------------------------------------
# Question 테이블 정의 클래스
#   -PK: id
# --------------------------------------------------------

class Question(DB.Model):

    id = DB.Column(DB.Integer, primary_key=True)
    subject = DB.Column(DB.String(200), nullable=False)
    content = DB.Column(DB.Text(), nullable=False)
    create_date = DB.Column(DB.DateTime(), nullable=False)


# --------------------------------------------------------
# Answer 테이블 정의 클래스
#   -PK: id
#   -FK: question_id
#   -REF_TB: Question
# --------------------------------------------------------

class Answer(DB.Model):

    id = DB.Column(DB.Integer, primary_key=True)
    question_id = DB.Column(DB.Integer, DB.ForeignKey('question.id', ondelete='CASCADE'))
    question = DB.relationship('Question', backref=DB.backref('answer_set',))
    content = DB.Column(DB.Text(), nullable=False)
    create_date = DB.Column(DB.DateTime(), nullable=False)

Flask_AI/D1023/DBWEB/__init__.py
# -------------------------------------------------------------
# Flask Framework에서 WebServer 구동 파일
#  - 파일명: app.py
# -------------------------------------------------------------

# 모듈 로딩
from flask import Flask


# DB관련 설정
import config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

DB = SQLAlchemy()           #
MIGRATE = Migrate()



# -------------------------------------------------------------
# Application 생성 함수
#  - 함수명: create_app
# -------------------------------------------------------------


def create_app():

    # flask web server 인스턴스 생성
    APP = Flask(__name__)


    ## 점프 투 플라스트 p.51--------------------
    # DB 관련 초기화 설정
    APP.config.from_object(config)

    # DB 초기화 및 앱 연동
    DB.init_app(APP)
    MIGRATE.init_app(APP, DB)

    # DB 클래스 정의 모듈 로딩
    from .models import models


    # URL 처리 모듈
    from .views import main_view, answer_view
    APP.register_blueprint(main_view.mainBP)
    APP.register_blueprint(answer_view.AnswerBP)


    return APP
    '''
    # URL 즉, 클라이언트 요청 페이지 주소를 보여줄 기능 함수
    def printPage():
        return "<h1>Hello~~~^A^</h1>"


    # URL 처리 함수 연결
    APP.add_url_rule('/', view_func=printPage, endpoint='INDEX')
     
    [flask routes 결과]
            Endpoint  Methods  Rule
        --------  -------  -----------------------
        INDEX     GET      /
        static    GET      /static/<path:filename>

    ## 라우팅!!!!-------------------------------------------------
    # 아래와 같은 결과
    # APP.add_url_rule('/', view_func=printPage, endpoint='INDEX')
    @APP.route('/', endpoint='INDEX')
    def printPage():
        return "<h1>Hello~~~^A^</h1>"
    
    '''

Flask_AI/D1023/DBWEB/views/answer_view.py
from datetime import datetime

from flask import Blueprint, url_for, request
from werkzeug.utils import redirect

from DBWEB import DB
from DBWEB.models.models import Question, Answer

AnswerBP = Blueprint('answer', __name__, url_prefix='/answer', template_folder='templates')


# 라우팅
@AnswerBP.route('/create/<int:question_id>', methods=('POST',))
def create(question_id):
    q = Question.query.get_or_404(question_id)
    content = request.form['content']   # POST 폼 방식으로 전송된 데이터 항목 중 content 값

    answer = Answer(content=content, create_date=datetime.now())
    q.answer_set.append(answer)         # Question 테이블에 answer 인스턴스 연결
                                        # 질문에 달린    답변 개념

    DB.session.commit()

    return redirect(url_for('MAIN.questionItem', question_id=question_id))

Flask_AI/D1023/DBWEB/views/main_view.py
# --------------------------------------------------
# Flask Framework에서 모듈단위 URL 처리 파일
#   - 파일명: main_view.py
# --------------------------------------------------

# 모듈 로딩
from flask import Blueprint, render_template

from DBWEB.models.models import Question

# Blueprint 인스턴스 생성
mainBP = Blueprint('MAIN',
                   import_name=__name__,
                   url_prefix='/',
                   template_folder='templates')

# http://localhost:5000/URL 처리 라우팅 함수 정의
@mainBP.route("/")
def index():
    return render_template('index.html', name='홍길동')


# http://localhost:5000/URL 처리 라우팅 함수 정의
@mainBP.route("/qlist")
def printList():
    # DB에서 조회한 결과를 HTML 파일로 전달
    q_list = Question.query.all()
    return render_template('question_list.html', question_list=q_list )


# http://localhost:5000/URL 처리 라우팅 함수 정의
@mainBP.route("/qdetail/<int:question_id>")
def questionItem(question_id):
    # DB에서 조회한 1개의 question 인스턴스 전달
    q = Question.query.get(question_id)
    return render_template('question_detail.html', question=q )

Flask_AI/D1023/DBWEB/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🦕MyWeb🐟</title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">


</head>
<body>
    <h1> 나 집갈래 </h1>
    <p> {{name}} 휴가 쓰고 싶어요 </p>
</body>
</html>

Flask_AI/D1023/DBWEB/templates/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> 질문상세보기 </h1>
    <div id="q">
        <label>제목: </label>
        {{question.subject}}<br>

        <label>내용:</label>
        {{question.content}}<br>
    </div>

    <div>
        <h5> {{ question.answer_set|length}}개의 답변이 있습니다. </h5>
        <ul>
        {% for answer in question.answer_set %}
            <li>{{ answer.content }}</li>
        {% endfor %}
        </ul>
    </div>

    <div>
        <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post">
            <textarea name="content" id="content" rows="5" cols="20" placeholder="답글입력"></textarea>
            <input type="submit" value="답변">

        </form>
    </div>

    
</body>
</html>

Flask_AI/D1023/DBWEB/templates/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    #msg {
        color: red;
    }
</head>
<body>
    <h1>질문게시판</h1>

    <!-- 
    기존 html에서 고정된 갯수의 ul/ol 가 아니라, 사용자가 질문(ul/ol)을 추가함에 따라 동적으로 갯수가 변해야 함
    => 반복문으로 DB에서 로드!
    -->
    <h3>Table Ver.</h3>
    <table border="1">
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>내용</th>
            <th>날짜</th>

        </tr>

        {% if question_list %}
        
            {% for question in question_list %}
            <tr>
                <!-- 질문의 제목만 출력 -->
                <td>{{question.id}}</td>
                <td><a href="/qdetail/{{question.id}}">{{question.subject}}</a></td>
                <td>{{question.create_date}}</td>
            </tr>
            {% endfor %}

        {% else %}
            <tr>
                <td class="msg" colspan="3">등록된 질문이 없습니다.</td>
            </tr>
        {% endif %}
    </table>

    <br><br><hr>

    <h3>List Ver.</h3>
    {% if question_list %}
    <ol>
        {% for question in question_list %}
            <li>{{question.id}}</li>
            <li><a href="/qdetail/{{question.id}}">{{question.subject}}</a></li>
            <li>{{question.content}}}}</li>
        {% endfor %}
    </ol>
    {% else %}
        <p class="msg">등록된 질문이 없습니다.</p>
    {% endif %}
</body>
</html>